# area of the environment
area:
 x_min: 0
 x_max: 500
 y_min: 0
 y_max: 500

#all static and dynamic obstacles 
obstacles:
 - # wall 1
  centroid_x: 150 # centroid of the obstacle
  centroid_y: 150 # centroid of the obstacle
  dx: 30 # width of the obstacle
  dy: 120 # height of the obstacle
  orientation: 0 # angle of the obstacle
  velocity_x: 0 # velocity of the obstacle
  velocity_y: 0 # velocity of the obstacle
  acc_x: 0 # acceleration of the obstacle
  acc_y: 0 # acceleration of the obstacle

 - # wall 2
  centroid_x: 300 # centroid of the obstacle
  centroid_y: 200 # centroid of the obstacle
  dx: 30 # width of the obstacle
  dy: 120 # height of the obstacle
  orientation: 0 # angle of the obstacle
  velocity_x: 0 # velocity of the obstacle
  velocity_y: 0 # velocity of the obstacle
  acc_x: 0 # acceleration of the obstacle
  acc_y: 0 # acceleration of the obstacle

#  - #vehicle 1 - move right
#   centroid_x: 100
#   centroid_y: 100
#   dx: 4
#   dy: 2
#   orientation: 0
#   velocity_x: 0.01
#   velocity_y: 0
#   acc_x: 0
#   acc_y: 0

#  - #vehicle 2 - move down
#   centroid_x: 300
#   centroid_y: 200
#   dx: 2
#   dy: 5
#   orientation: 0 
#   velocity_x: 0
#   velocity_y: -0.01
#   acc_x: 0
#   acc_y: 0

#  - #vehicle 3 - parked
#   centroid_x: 400
#   centroid_y: 350
#   dx: 4
#   dy: 2
#   orientation: -30
#   velocity_x: 0
#   velocity_y: 0
#   acc_x: 0
#   acc_y: 0
